USE [master]
GO

/****** Object:  Database [Teste]    Script Date: 05/08/2016 16:51:21 ******/
CREATE DATABASE [Teste]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Teste', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLDEVELOPER\MSSQL\DATA\Teste.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Teste_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLDEVELOPER\MSSQL\DATA\Teste_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Teste] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Teste].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Teste] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Teste] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Teste] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Teste] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Teste] SET ARITHABORT OFF 
GO

ALTER DATABASE [Teste] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Teste] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Teste] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Teste] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Teste] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Teste] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Teste] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Teste] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Teste] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Teste] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Teste] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Teste] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Teste] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Teste] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Teste] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Teste] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Teste] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Teste] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Teste] SET RECOVERY FULL 
GO

ALTER DATABASE [Teste] SET  MULTI_USER 
GO

ALTER DATABASE [Teste] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Teste] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Teste] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Teste] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Teste] SET  READ_WRITE 
GO

